### ISSUE TITLE
虚拟化的GPU出错

### ISSUE THREAD

**Issue by JialeiHuang** [iiisthu/gpupool#10]
![image](https://user-images.githubusercontent.com/39868647/98939072-d1ddf700-2523-11eb-81b5-1d87b4940b14.png)
cheng'x程序运行时虚拟化的GPU出现段错误。
本pod从library/ubuntu-pytorch:v1.50内的镜像启动

**Comment by JialeiHuang** [comment]
![image](https://user-images.githubusercontent.com/39868647/98939361-4a44b800-2524-11eb-8167-702f1355685e.png)
现在错误如下，已经尝试export LD_LIBRARY_PATH=/usr/lib/orion:$LD_LIBRARY_PATH，仍然无效

**Comment by JialeiHuang** [comment]
问题解决
torch和tf要使用特殊版本，安装指令见：https://pypi.virtaitech.com/

**Comment by fpshuang** [comment]
@JialeiHuang 我在pod下装了orion所列的whl，但是还是报一样的错误。是因为我用了conda吗？
