### ISSUE TITLE
apply -f quota.yaml fail

### ISSUE THREAD

**Issue by duchenzhuang** [iiisthu/gpupool#12]
在apply .yaml时候出现一下问题：
duchenzhuang@duchenzhuangdeMacBook-Pro ~ % kubectl -n duchenzhuang apply -f gputool/quota.yaml
E1112 21:56:47.578436   15025 request.go:975] Unexpected error when reading response body: context deadline exceeded (Client.Timeout or context cancellation while reading body)
error: unexpected error when reading response body. Please retry. Original error: context deadline exceeded (Client.Timeout or context cancellation while reading body)

yaml文件：
![image](https://user-images.githubusercontent.com/54940144/98949240-694a4680-2532-11eb-9fea-ea96f772f83b.png)

**Comment by fingertap** [comment]
It should be a network problem. Try ping harbor.iiis.co first. The VPN may be dead. See [here](https://github.com/kubernetes/kubernetes/issues/89107).
