### ISSUE TITLE
Failed to build my own docker images from these in 172.16.112.220:30006/library/

### ISSUE THREAD

**Issue by AlvinWen428** [iiisthu/gpupool#13]
我想build一个自己的docker镜像，所以写了一个Dockerfile，具体内容如下：
```FROM  172.16.112.220:30006/library/orion-client-2.4.2:cu10.1_cudnn7_ubuntu18.04-base
ENV ORION_VGPU 1
WORKDIR /root
RUN wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh -O anaconda.sh
RUN bash /root/anaconda.sh -b -p /root/anaconda
```
 
然后我在我自己的电脑上build这个Dockerfile，会出现这个错误：
![2020-11-13 21-41-14 的屏幕截图](https://user-images.githubusercontent.com/34668706/99082042-9bc17580-25fe-11eb-9bc7-c432324ef166.png)

**Comment by fingertap** [comment]
client pod 是需要依赖server服务的，如果没有部署orion-server就会报这个错。将打好的镜像由集群拉取建立Pod，本地运行容器会报错。请参考我们提供的[例子](https://github.com/iiisthu/gpupool/blob/master/image_build.md)制作镜像。
