### ISSUE TITLE
kubernetes 显示的pod ip 实际上是node ip

### ISSUE THREAD

**Issue by zzhao1998** [iiisthu/gpupool#16]
```
kubectl get pod -o wide
NAME                               READY   STATUS      RESTARTS   AGE     IP               NODE             NOMINATED NODE   READINESS GATES
my-tf-7f4668b9c4-lbvr7             1/1     Running     0          2d8h    172.16.112.199   k8sdeploy-n199   <none>           <none>
my-torch-2-7584ddb48-8g9tr         1/1     Running     0          3d3h    172.16.112.189   k8sdeploy-n189   <none>           <none>
my-torch-f98f57cf4-zzbz5           1/1     Running     0          5d2h    172.16.112.199   k8sdeploy-n199   <none>           <none>
my-torch-master-7f7d7f6496-278n6   0/1     Completed   1          5m46s   172.16.112.189   k8sdeploy-n189   <none>           <none>
```
查询时实际上显示的是node ip
但是根据网上的资料这里实际上应该显示pod ip
https://www.digitalocean.com/community/tutorials/how-to-inspect-kubernetes-networking#:~:text=To%20find%20the%20cluster%20IP,and%20the%20pod's%20cluster%20IP.&text=The%20IP%20column%20will%20contain,IP%20address%20for%20each%20pod.

使用环境变量的方法显示的也是实际上的node ip而不是pod ip
https://stackoverflow.com/questions/30746888/how-to-know-a-pods-own-ip-address-from-inside-a-container-in-the-pod

请问这个是集群的问题吗？

**Comment by yunfeng9900-git** [comment]
之所以有这种情况，因为我们配置外部访问k8s的pod时，使用hostNetwork: true，此时podIP就是所在node的IP
