### ISSUE TITLE
Fail to build docker image based on image in harbor.iiis.co

### ISSUE THREAD

**Issue by nuzant** [iiisthu/gpupool#17]
I tried to build a image based on 172.16.112.220:30006/library/ubuntu-pytorch:1.5.0, but failed on the first step:

nuzant@nuzant-911MT:~/ray_experiments/distributed/test$ sudo docker build . -t test:v0
Sending build context to Docker daemon  31.74kB
Step 1/2 : FROM 172.16.112.220:30006/library/ubuntu-pytorch:1.5.0
Get https://172.16.112.220:30006/v2/: http: server gave HTTP response to HTTPS client

After which docker process stopped. What is the problem and how can I fix? Thanks!

Screenshot in ![here](https://user-images.githubusercontent.com/23146120/103969484-f6132880-51a0-11eb-9985-bd5fdb789e96.png).

**Comment by fingertap** [comment]
Did you trust the harbor in docker? Try add `harbor.iiis.co` into the trust list of harbor and see whether this problem exists.

BTW, use IP address of harbor is not recommended, as we may change the IP of harbor. Use domain name instead: `harbor.iiis.co`.

**Comment by fingertap** [comment]
Also, you don't need to add the port number `30006` in the address, as we already did port mapping (which could change, so your code may fail once the port is no longer `30006`).

**Comment by fingertap** [comment]
Check out the [doc](https://github.com/iiisthu/gpupool/blob/master/image_build.md#%E4%BF%A1%E4%BB%BB%E9%9B%86%E7%BE%A4-harbor) for how to trust our harbor.
