### ISSUE TITLE
Cephfs PVC fail to init

### ISSUE THREAD

**Issue by xssstory** [iiisthu/gpupool#5]
I try to create a cephfs-pvc by ceph-pvc-example.yaml and mount it in a pod, but the pod is always pending.

I use "kubectl describe pod" and get
  ----     ------            ----   ----               -------
 Events:
  Type     Reason            Age    From               Message

  Warning  FailedScheduling  7m50s  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
  Warning  FailedScheduling  6m37s  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
  ----     ------            ----   ----               -------
I use "kubectl describe PersistentVolumeClaims" and get
  ----     ------              ----                 ----                         -------
Events:
  Type     Reason              Age                  From                         Message

  Warning  ProvisioningFailed  54s (x102 over 26m)  persistentvolume-controller  storageclass.storage.k8s.io "cephfs" not found
  ----     ------            ----   ----               -------
What is wrong and how to resolve this problem?

**Comment by fingertap** [comment]
Currently the cephfs has a writing problem. You can use NFS + local disk for now. We are working on the problem and will update the process here.

**Comment by yunfeng9900-git** [comment]
Now user can create  a pod mounting cephfs pvc successfully.  We will test the cephfs  and troubleshoot the writing problem.

**Comment by fingertap** [comment]
We will discuss the writing performance of Ceph in another issue. Closing.
