### ISSUE TITLE
failed to get config from harbor.iiis.co:31388

### ISSUE THREAD

**Issue by JialeiHuang** [iiisthu/gpupool#6]
![image](https://user-images.githubusercontent.com/39868647/98796576-80ac0580-2446-11eb-88c0-2cf3dcdf555d.png)

**Comment by fingertap** [comment]
目前初期服务器不稳定，遇见internal error请及时联系尹老师

**Comment by yunfeng9900-git** [comment]
该问题原因：服务对应的pod挂了，正常会自动重新拉起pod，但在另一个node上拉起pod时，无法拉取镜像。因为镜像仓库故障。把镜像仓库问题解决，该问题自动解除了。
