### ISSUE TITLE
failed to access /pvc/ 

### ISSUE THREAD

**Issue by JialeiHuang** [iiisthu/gpupool#7]
bash: cd: pvc: Stale file handle
![image](https://user-images.githubusercontent.com/39868647/98806704-8e688780-2454-11eb-823c-3b9a53004785.png)

I can access my pvc yesterday, but things doesn't work now.

**Comment by yunfeng9900-git** [comment]
该问题产生原因：当pod挂接nfs后，当nfs后端存储系统切换成华为存储，变产出该问题。
解决办法：用户可以自行重新拉起pod。
待测试的解决办法：管理员重新拉起nfs-client对应的pod。
