### ISSUE TITLE
Failed to apply for GPU with ubuntu-tf-example.yaml

### ISSUE THREAD

**Issue by nuzant** [iiisthu/gpupool#8]
After cluster upgrade I can not apply for GPU resources anymore. I tried to create pod with 'ubuntu-tf-example.yaml' but it remains pending. 

> NAME                                 READY   STATUS    RESTARTS   AGE
> my-first-ubuntu-tf-7b98cdfb4-5nb2q   0/1     Pending   0          6s

Output of  'kubectl desribe pod my-first-ubuntu-tf-7b98cdfb4-5nb2q' shows that insufficient virtaitech.com/gpu.

> Name:           my-first-ubuntu-tf-7b98cdfb4-5nb2q
> Namespace:      mzy20
> Priority:       0
> Node:           <none>
> Labels:         name=my-ubuntu-tf
>                 pod-template-hash=7b98cdfb4
> Annotations:    <none>
> Status:         Pending
> IP:             
> IPs:            <none>
> Controlled By:  ReplicaSet/my-first-ubuntu-tf-7b98cdfb4
> Containers:
>   orion-client-hvd:
>     Image:      172.16.112.220:30006/library/ubuntu-tensorflow:2.3.0
>     Port:       <none>
>     Host Port:  <none>
>     Command:
>       bash
>       -c
>       --
>     Args:
>       while true; do sleep 30; done;
>     Limits:
>       cpu:                 1
>       memory:              1Gi
>       virtaitech.com/gpu:  1
>     Requests:
>       cpu:                 1
>       memory:              1Gi
>       virtaitech.com/gpu:  1
>     Environment:
>       ORION_GMEM:        10000
>       ORION_RATIO:       100
>       ORION_VGPU:        1
>       ORION_RESERVED:    0
>       ORION_CROSS_NODE:  1
>       ORION_GROUP_ID:     (v1:metadata.uid)
>     Mounts:
>       /var/run/secrets/kubernetes.io/serviceaccount from default-token-z4gqv (ro)
> Conditions:
>   Type           Status
>   PodScheduled   False 
> Volumes:
>   default-token-z4gqv:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  default-token-z4gqv
>     Optional:    false
> QoS Class:       Guaranteed
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> Events:
>   Type     Reason            Age   From               Message
>   ----     ------            ----  ----               -------
>   Warning  FailedScheduling  61s   default-scheduler  0/25 nodes are available: 25 Insufficient virtaitech.com/gpu.
>   Warning  FailedScheduling  60s   default-scheduler  0/25 nodes are available: 25 Insufficient virtaitech.com/gpu.

Is there anything wrong with my operation or there are other bugs? How can I fix the problem?

**Comment by yunfeng9900-git** [comment]
Through changing orion's ip to domain name,the problem is fixed. Certainly, only the cluster administrator can do it.
