### ISSUE TITLE
Fail to apply new quota

### ISSUE THREAD

**Issue by IrisLi17** [iiisthu/gpupool#9]
After running `kubectl apply -f quota.yaml`, I got the following error message: 
E1112 15:49:18.922700   89281 request.go:975] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
error: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout exceeded while reading body)

I have retried many times but it doesn't work.

**Comment by fingertap** [comment]
This is a network problem. Make sure that you have VPN on.
